# Example Docker compose file to run the service
services:
  beanbook:
    image: zeletrik/beanbook:latest
    ports:
      - "8001:8001"
    environment:
      - DATASOURCE_PATH=/data/beanbook.db
    volumes:
      - beanbook-data:/data

volumes:
  beanbook-data:
